# Generated by Django 5.2.16 on 2026-07-11 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obligation_code', models.CharField(max_length=64, verbose_name='Código de obligación')),
                ('obligation_name', models.CharField(max_length=255, verbose_name='Obligación')),
                ('period', models.CharField(help_text='Formato MM/YYYY, p.ej. 07/2026', max_length=7, verbose_name='Período fiscal')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('WAITING_INFORMATION', 'Esperando información'), ('READY', 'Listo'), ('COMPLETED', 'Completado'), ('OVERDUE', 'Vencido'), ('NOT_APPLICABLE', 'No aplica'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('google_calendar_event_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('google_calendar_id', models.CharField(blank=True, help_text='ID del calendario compartido donde vive el evento.', max_length=255)),
                ('google_sync_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error')], db_index=True, default='PENDING', max_length=16)),
                ('google_sync_error', models.TextField(blank=True)),
                ('google_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('google_etag', models.CharField(blank=True, max_length=255)),
                ('google_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deadlines', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='clients.client')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deadlines', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deadlines', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Vencimiento',
                'verbose_name_plural': 'Vencimientos',
                'ordering': ['due_date', 'obligation_code'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('observation', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('google_sync_result', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadline_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='deadlines.deadline')),
            ],
            options={
                'verbose_name': 'Auditoría de vencimiento',
                'verbose_name_plural': 'Auditorías de vencimientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deadline',
            index=models.Index(fields=['google_sync_status', 'updated_at'], name='deadlines_d_google__8414e9_idx'),
        ),
        migrations.AddIndex(
            model_name='deadline',
            index=models.Index(fields=['status', 'due_date'], name='deadlines_d_status_0751fe_idx'),
        ),
    ]
