# Generated by Django 5.2.16 on 2026-07-11 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_email', models.EmailField(blank=True, max_length=254)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True)),
                ('shared_calendar_id', models.CharField(blank=True, max_length=255)),
                ('shared_calendar_name', models.CharField(default='Vencimientos – Estudio Contable', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_calendar_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexión Google Calendar',
                'verbose_name_plural': 'Conexiones Google Calendar',
                'ordering': ['-updated_at'],
            },
        ),
    ]
