# Generated by Django 5.2.16 on 2026-07-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuitalizer_api_key', models.CharField(blank=True, max_length=255)),
                ('cuit_lookup_url_template', models.CharField(blank=True, help_text='Ej: https://tu-api.example/cuit/{cuit}', max_length=500)),
                ('cuit_lookup_api_key', models.CharField(blank=True, max_length=255)),
                ('afip_sdk_access_token', models.CharField(blank=True, max_length=255)),
                ('afip_sdk_cuit', models.CharField(blank=True, default='20-40937847-2', help_text='CUIT del certificado / entorno Afip SDK. En desarrollo: 20-40937847-2', max_length=13)),
                ('afip_sdk_production', models.BooleanField(default=False, help_text='Usar producción ARCA (requiere certificado propio en Afip SDK).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del estudio',
                'verbose_name_plural': 'Configuración del estudio',
            },
        ),
    ]
