# Generated by Django 5.2.16 on 2026-07-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_studiosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiosettings',
            name='app_base_url',
            field=models.URLField(blank=True, help_text='Ej: https://app.fabregad.com.ar', max_length=500, verbose_name='URL base de la app'),
        ),
        migrations.AddField(
            model_name='studiosettings',
            name='google_oauth_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Client ID'),
        ),
        migrations.AddField(
            model_name='studiosettings',
            name='google_oauth_client_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Client Secret'),
        ),
        migrations.AddField(
            model_name='studiosettings',
            name='google_oauth_redirect_uri',
            field=models.URLField(blank=True, help_text='Ej: https://app.fabregad.com.ar/integraciones/google/callback/', max_length=500, verbose_name='URI de redirección OAuth'),
        ),
    ]
