# Generated by Django 5.2.16 on 2026-07-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_google_oauth_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiosettings',
            name='app_base_url',
            field=models.CharField(blank=True, help_text='Ej: https://app.fabregad.com.ar', max_length=500, verbose_name='URL base de la app'),
        ),
        migrations.AlterField(
            model_name='studiosettings',
            name='google_oauth_redirect_uri',
            field=models.CharField(blank=True, help_text='Ej: https://app.fabregad.com.ar/integraciones/google/callback/', max_length=500, verbose_name='URI de redirección OAuth'),
        ),
    ]
